# Generated by Django 3.0.5 on 2020-08-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200831_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='polo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parte',
            name='tipo_pessoa',
            field=models.CharField(choices=[('Pessoa Física', 'Pessoa Física'), ('Pessoa Jurídica', 'Pessoa Jurídica')], max_length=50),
        ),
    ]
