# Generated by Django 3.0.5 on 2020-08-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200831_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunto',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='movimento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentocnj',
            name='movimento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentocnj',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
