# Generated by Django 3.0.5 on 2020-08-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunto',
            name='cod_assunto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='cod_classe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentocnj',
            name='cod_movimento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
